apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 

kind: Deployment 

metadata: 

  name: Naveen-aspdotnet

spec: 

  selector: 

    matchLabels: 

      app:  Naveen-aspdotnet-selectors 

  replicas: 5 # tells deployment to run 2 pods matching the template 

  template:

    metadata: 

      labels: 

        app:  Naveen-aspdotnet-label 

    spec: 

      containers: 

      - name:  Naveen-aspdotnet 

        image: gsrini23/dotnetapp:#{Build.BuildId}#

        ports: 

        - containerPort: 80 

--- 

# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  

kind: Service 

apiVersion: v1 

metadata: 

  name:  Naveen-aspdotnet-service

spec: 

  selector: 

    app: aspdotnet

  ports: 

  - protocol: TCP 

    port: 80 

    targetPort: 80 

  type: LoadBalancer 
